/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef APP_H
#define APP_H

#include <string>

namespace CICD {
    class Greeter {
        public:
        std::string greeting();
        int carre(int a){ return a*a;}
    };
}

#endif
